

export const departamentos = [
    { id: 'Amazonas', nombre: 'Amazonas' },
    { id: 'Ancash', nombre: 'Ancash' },
    { id: 'Apurimac', nombre: 'Apurimac' },
    { id: 'Arequipa', nombre: 'Arequipa' },
    { id: 'Ayacucho', nombre: 'Ayacucho' },
    { id: 'Cajamarca', nombre: 'Cajamarca' },
    { id: 'Callao', nombre: 'Callao' },
    { id: 'Cusco', nombre: 'Cusco' },
    { id: 'Huancavelica', nombre: 'Huancavelica' },
    { id: 'Huanuco', nombre: 'Huanuco' },
    { id: 'Ica', nombre: 'Ica' },
    { id: 'Junin', nombre: 'Junin' },
    { id: 'La_Libertad', nombre: 'La Libertad' },
    { id: 'Lambayeque', nombre: 'Lambayeque' },
    { id: 'Lima', nombre: 'Lima' },
    { id: 'Loreto', nombre: 'Loreto' },
    { id: 'Madre_de_Dios', nombre: 'Madre de Dios' },
    { id: 'Moquegua', nombre: 'Moquegua' },
    { id: 'Pasco', nombre: 'Pasco' },
    { id: 'Piura', nombre: 'Piura' },
    { id: 'Puno', nombre: 'Puno' },
    { id: 'San_Martin', nombre: 'San Martin' },
    { id: 'Tacna', nombre: 'Tacna' },
    { id: 'Tumbes', nombre: 'Tumbes' },
    { id: 'Ucayali', nombre: 'Ucayali' }

];

export const distritosPorDepartamento = {
    Amazonas: [
        { id: 'Chachapoyas', nombre: 'Chachapoyas' },
        { id: 'Bagua', nombre: 'Bagua' },
        { id: 'Bongara', nombre: 'Bongara' },
        { id: 'Condorcanqui', nombre: 'Condorcanqui' },
        { id: 'Luya', nombre: 'Luya' },
        { id: 'Rodriguez de Mendoza', nombre: 'Rodriguez de Mendoza' },
        { id: 'Utcubamba', nombre: 'Utcubamba' },
        { id: 'Utcubamba', nombre: 'Utcubamba' },
        { id: 'Utcubamba', nombre: 'Utcubamba' },
    ],
    Ancash: [
        { id: 'Huaraz', nombre: 'Huaraz' },
        { id: 'Aija', nombre: 'Aija' },
        { id: 'Antonio Raymondi', nombre: 'Antonio Raymondi' },
        { id: 'Asuncion', nombre: 'Asuncion' },
        { id: 'Bolognesi', nombre: 'Bolognesi' },
        { id: 'Carhuaz', nombre: 'Carhuaz' },
        { id: 'Carlos Fermin Fitzcarrald', nombre: 'Carlos Fermin Fitzcarrald' },
        { id: 'Casma', nombre: 'Casma' },
        { id: 'Corongo', nombre: 'Corongo' },
        { id: 'Huari', nombre: 'Huari' },
        { id: 'Huarmey', nombre: 'Huarmey' },
        { id: 'Huaylas', nombre: 'Huaylas' },
        { id: 'Mariscal Luzuriaga', nombre: 'Mariscal Luzuriaga' },
        { id: 'Ocros', nombre: 'Ocros' },
        { id: 'Pallasca', nombre: 'Pallasca' },
        { id: 'Pomabamba', nombre: 'Pomabamba' },
        { id: 'Recuay', nombre: 'Recuay' },
        { id: 'Santa', nombre: 'Santa' },
        { id: 'Sihuas', nombre: 'Sihuas' },
        { id: 'Yungay', nombre: 'Yungay' },
    ],
    Apurimac: [
        { id: 'Abancay', nombre: 'Abancay' },
        { id: 'Andahuaylas', nombre: 'Andahuaylas' },
        { id: 'Antabamba', nombre: 'Antabamba' },
        { id: 'Aymaraes', nombre: 'Aymaraes' },
        { id: 'Cotabambas', nombre: 'Cotabambas' },
        { id: 'Chincheros', nombre: 'Chincheros' },
        { id: 'Grau', nombre: 'Grau' },
    ],
    Arequipa: [
        { id: 'Arequipa', nombre: 'Arequipa' },
        { id: 'Camana', nombre: 'Camana' },
        { id: 'Caraveli', nombre: 'Caraveli' },
        { id: 'Castilla', nombre: 'Castilla' },
        { id: 'Caylloma', nombre: 'Caylloma' },
        { id: 'Condesuyos', nombre: 'Condesuyos' },
        { id: 'Islay', nombre: 'Islay' },
        { id: 'La Union', nombre: 'La Union' },
    ],
    Ayacucho: [
        { id: 'Huamanga', nombre: 'Huamanga' },
        { id: 'Cangallo', nombre: 'Cangallo' },
        { id: 'Huanca Sancos', nombre: 'Huanca Sancos' },
        { id: 'Huanta', nombre: 'Huanta' },
        { id: 'La Mar', nombre: 'La Mar' },
        { id: 'Lucanas', nombre: 'Lucanas' },
        { id: 'Parinacochas', nombre: 'Parinacochas' },
        { id: 'Pausa', nombre: 'Pausa' },
        { id: 'Sucre', nombre: 'Sucre' },
        { id: 'Victor Fajardo', nombre: 'Victor Fajardo' },
        { id: 'Vilcas Huaman', nombre: 'Vilcas Huaman' },
    ],
    Cajamarca: [
        { id: 'Cajamarca', nombre: 'Cajamarca' },
        { id: 'Cajabamba', nombre: 'Cajabamba' },
        { id: 'Celendin', nombre: 'Celendin' },
        { id: 'Chota', nombre: 'Chota' },
        { id: 'Contumaza', nombre: 'Contumaza' },
        { id: 'Cutervo', nombre: 'Cutervo' },
        { id: 'Hualgayoc', nombre: 'Hualgayoc' },
        { id: 'Jaen', nombre: 'Jaen' },
        { id: 'San Ignacio', nombre: 'San Ignacio' },
        { id: 'San Marcos', nombre: 'San Marcos' },
        { id: 'San Miguel', nombre: 'San Miguel' },
        { id: 'San Pablo', nombre: 'San Pablo' },
        { id: 'Santa Cruz', nombre: 'Santa Cruz' },
    ],
    Callao: [
        { id: 'Callao', nombre: 'Callao' },
    ],
    Cusco: [
        { id: 'Cusco', nombre: 'Cusco' },
        { id: 'Acomayo', nombre: 'Acomayo' },
        { id: 'Anta', nombre: 'Anta' },
        { id: 'Calca', nombre: 'Calca' },
        { id: 'Canas', nombre: 'Canas' },
        { id: 'Canchis', nombre: 'Canchis' },
        { id: 'Chumbivilcas', nombre: 'Chumbivilcas' },
        { id: 'Espinar', nombre: 'Espinar' },
        { id: 'La Convencion', nombre: 'La Convencion' },
        { id: 'Paruro', nombre: 'Paruro' },
        { id: 'Paucartambo', nombre: 'Paucartambo' },
        { id: 'Quispicanchi', nombre: 'Quispicanchi' },
        { id: 'Urubamba', nombre: 'Urubamba' },
    ],
    Huancavelica: [
        { id: 'Huancavelica', nombre: 'Huancavelica' },
        { id: 'Acobamba', nombre: 'Acobamba' },
        { id: 'Angaraes', nombre: 'Angaraes' },
        { id: 'Castrovirreyna', nombre: 'Castrovirreyna' },
        { id: 'Churcampa', nombre: 'Churcampa' },
        { id: 'Huaytara', nombre: 'Huaytara' },
        { id: 'Tayacaja', nombre: 'Tayacaja' },
    ],
    Huanuco: [
        { id: 'Huanuco', nombre: 'Huanuco' },
        { id: 'Ambo', nombre: 'Ambo' },
        { id: 'Dos de Mayo', nombre: 'Dos de Mayo' },
        { id: 'Huacaybamba', nombre: 'Huacaybamba' },
        { id: 'Huamalies', nombre: 'Huamalies' },
        { id: 'Huanuco', nombre: 'Huanuco' },
        { id: 'Lauricocha', nombre: 'Lauricocha' },
        { id: 'Leoncio Prado', nombre: 'Leoncio Prado' },
        { id: 'Marañon', nombre: 'Marañon' },
        { id: 'Pachitea', nombre: 'Pachitea' },
        { id: 'Puerto Inca', nombre: 'Puerto Inca' },
        { id: 'Yarowilca', nombre: 'Yarowilca' },
    ],
    Ica: [
        { id: 'Ica', nombre: 'Ica' },
        { id: 'Chincha', nombre: 'Chincha' },
        { id: 'Nazca', nombre: 'Nazca' },
        { id: 'Palpa', nombre: 'Palpa' },
        { id: 'Pisco', nombre: 'Pisco' },
    ],
    Junin: [
        { id: 'Huancayo', nombre: 'Huancayo' },
        { id: 'Concepcion', nombre: 'Concepcion' },
        { id: 'Chanchamayo', nombre: 'Chanchamayo' },
        { id: 'Jauja', nombre: 'Jauja' },
        { id: 'Junin', nombre: 'Junin' },
        { id: 'Satipo', nombre: 'Satipo' },
        { id: 'Tarma', nombre: 'Tarma' },
        { id: 'Yauli', nombre: 'Yauli' },
        { id: 'Chupaca', nombre: 'Chupaca' },
    ],
    La_Libertad: [
        { id: 'Trujillo', nombre: 'Trujillo' },
        { id: 'Ascope', nombre: 'Ascope' },
        { id: 'Bolivar', nombre: 'Bolivar' },
        { id: 'Chepen', nombre: 'Chepen' },
        { id: 'Gran Chimu', nombre: 'Gran Chimu' },
        { id: 'Julcan', nombre: 'Julcan' },
        { id: 'Otuzco', nombre: 'Otuzco' },
        { id: 'Pacasmayo', nombre: 'Pacasmayo' },
        { id: 'Pataz', nombre: 'Pataz' },
        { id: 'Sanchez Carrion', nombre: 'Sanchez Carrion' },
        { id: 'Santiago de Chuco', nombre: 'Santiago de Chuco' },
        { id: 'Viru', nombre: 'Viru' },
    ],
    Lambayeque: [
        { id: 'Chiclayo', nombre: 'Chiclayo' },
        { id: 'Ferreñafe', nombre: 'Ferreñafe' },
        { id: 'Lambayeque', nombre: 'Lambayeque' },
        { id: 'Lima', nombre: 'Lima' },
        { id: 'Olmos', nombre: 'Olmos' },
        { id: 'Tucume', nombre: 'Tucume' },
    ],
    Lima: [
        { id: 'Lima', nombre: 'Lima' },
        { id: 'Barranca', nombre: 'Barranca' },
        { id: 'Cajatambo', nombre: 'Cajatambo' },
        { id: 'Canta', nombre: 'Canta' },
        { id: 'Cañete', nombre: 'Cañete' },
        { id: 'Huaral', nombre: 'Huaral' },
        { id: 'Huarochiri', nombre: 'Huarochiri' },
        { id: 'Huaura', nombre: 'Huaura' },
        { id: 'Oyon', nombre: 'Oyon' },
        { id: 'Yauyos', nombre: 'Yauyos' },
    ],
    Loreto: [
        { id: 'Maynas', nombre: 'Maynas' },
        { id: 'Alto Amazonas', nombre: 'Alto Amazonas' },
        { id: 'Loreto', nombre: 'Loreto' },
        { id: 'Mariscal Ramon Castilla', nombre: 'Mariscal Ramon Castilla' },
        { id: 'Requena', nombre: 'Requena' },
        { id: 'Ucayali', nombre: 'Ucayali' },
    ],
    Madre_de_Dios: [
        { id: 'Tambopata', nombre: 'Tambopata' },
        { id: 'Manu', nombre: 'Manu' },
        { id: 'Tahuamanu', nombre: 'Tahuamanu' },
    ],
    Moquegua: [
        { id: 'Mariscal Nieto', nombre: 'Mariscal Nieto' },
        { id: 'General Sanchez Cerro', nombre: 'General Sanchez Cerro' },
        { id: 'Ilo', nombre: 'Ilo' },
    ],
    Pasco: [
        { id: 'Pasco', nombre: 'Pasco' },
        { id: 'Daniel Alcides Carrion', nombre: 'Daniel Alcides Carrion' },
        { id: 'Oxapampa', nombre: 'Oxapampa' },
    ],
    Piura: [
        { id: 'Piura', nombre: 'Piura' },
        { id: 'Ayabaca', nombre: 'Ayabaca' },
        { id: 'Huancabamba', nombre: 'Huancabamba' },
        { id: 'Morropon', nombre: 'Morropon' },
        { id: 'Paita', nombre: 'Paita' },
        { id: 'Sullana', nombre: 'Sullana' },
        { id: 'Talara', nombre: 'Talara' },
    ],
    Puno: [
        { id: 'Puno', nombre: 'Puno' },
        { id: 'Azangaro', nombre: 'Azangaro' },
        { id: 'Carabaya', nombre: 'Carabaya' },
        { id: 'Chucuito', nombre: 'Chucuito' },
        { id: 'El Collao', nombre: 'El Collao' },
        { id: 'Huancane', nombre: 'Huancane' },
        { id: 'Lampa', nombre: 'Lampa' },
        { id: 'Melgar', nombre: 'Melgar' },
        { id: 'Moho', nombre: 'Moho' },
        { id: 'San Antonio de Putina', nombre: 'San Antonio de Putina' },
        { id: 'San Roman', nombre: 'San Roman' },
        { id: 'Sandia', nombre: 'Sandia' },
        { id: 'Yunguyo', nombre: 'Yunguyo' },
    ],
    San_Martin: [
        { id: 'Moyobamba', nombre: 'Moyobamba' },
        { id: 'Bellavista', nombre: 'Bellavista' },
        { id: 'El Dorado', nombre: 'El Dorado' },
        { id: 'Huallaga', nombre: 'Huallaga' },
        { id: 'Lamas', nombre: 'Lamas' },
        { id: 'Mariscal Caceres', nombre: 'Mariscal Caceres' },
        { id: 'Picota', nombre: 'Picota' },
        { id: 'Rioja', nombre: 'Rioja' },
        { id: 'San Martin', nombre: 'San Martin' },
        { id: 'Tocache', nombre: 'Tocache' },
    ],
    Tacna: [
        { id: 'Tacna', nombre: 'Tacna' },
        { id: 'Candarave', nombre: 'Candarave' },
        { id: 'Jorge Basadre', nombre: 'Jorge Basadre' },
        { id: 'Tarata', nombre: 'Tarata' },
    ],
    Tumbes: [
        { id: 'Tumbes', nombre: 'Tumbes' },
        { id: 'Contralmirante Villar', nombre: 'Contralmirante Villar' },
        { id: 'Zarumilla', nombre: 'Zarumilla' },
    ],
    Ucayali: [
        { id: 'Coronel Portillo', nombre: 'Coronel Portillo' },
        { id: 'Atalaya', nombre: 'Atalaya' },
        { id: 'Padre Abad', nombre: 'Padre Abad' },
        { id: 'Purus', nombre: 'Purus' },
    ]

};
